catalog/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import *
from skypro_online_store import settings

urlpatterns = [
    path('', main_menu, name='main_menu'),
    path('product/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('contact_us/', contact_us, name='contact_us'),
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('create_product', ProductCreateView.as_view(), name='product_create'),
    path('update_product/<int:pk>', ProductUpdateView.as_view(), name='product_update'),
    path('product_delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skypro_online_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls'), name="catalog"),
    path('', include('article.urls'), name="article"),
    path('', include('users.urls'), name='users'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import RegisterView, ResetPasswordView

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset_password'),
]

catalog/models.py
from django.db import models

from skypro_online_store import settings
from skypro_online_store.settings import NULLABLE


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=100, )
    description = models.TextField()
    image = models.ImageField(upload_to='images/', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price_per_unit = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='products',
        verbose_name="Владелец",
        **NULLABLE,
    )
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        permissions = [
            ("can_change_description", "Can change description"),
            ("can_change_category", "Can change category"),
            ("can_change_is_published", "Can change is_published"),
        ]


class Version(models.Model):
    version_name = models.CharField(max_length=200)
    version_number = models.CharField(max_length=100, default='1.0.0')
    current_version = models.BooleanField(default=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, **NULLABLE, related_name='versions')

    def __str__(self):
        return f"{self.product.name} {self.version_number}"

    class Meta:
        verbose_name = 'Version'
        verbose_name_plural = 'Versions'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ['updated_at', 'created_at', 'owner']

    def __init__(self, *args, **kwargs):
        self.restricted_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                                 'радар']
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_name(self):
        name = self.cleaned_data['name']
        for word in self.restricted_words:
            if word in name:
                raise forms.ValidationError(f"Слово {word} запрещено!!")
        return self.cleaned_data['name']

    def clean_description(self):
        description = self.cleaned_data['description']
        for word in self.restricted_words:
            if word in description:
                raise forms.ValidationError(f"Слово {word} запрещено!!")
        return self.cleaned_data['description']


class VersionCreateForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ('version_name', 'version_number', 'current_version')

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView

from catalog.forms import ProductForm
from catalog.models import Product, Version
from catalog.services import get_categories


def main_menu(request):
    return render(request, 'main_menu.html')


class ProductListView(ListView):
    model = Product
    template_name = 'product_list.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        products_with_versions = []
        for product in context['products']:
            active_version = Version.objects.filter(product=product, current_version=True).first()

            products_with_versions.append({
                'product': product,
                'active_version': active_version,
            })

        context['products_with_versions'] = products_with_versions
        context['categories'] = get_categories()
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product_detail.html'


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('product_list')
    template_name = 'product_create.html'
    permission_required = [
        'catalog.can_change_description',
        'catalog.can_change_category',
        'catalog.can_change_is_published'
    ]

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)

        user = self.request.user

        if user.groups.filter(name='manager').exists():
            allowed_fields = ['description', 'category', 'is_published']
            form.fields = {key: form.fields[key] for key in allowed_fields if key in form.fields}

        return form


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'product_create.html'
    permission_required = [
        'catalog.can_change_description',
        'catalog.can_change_category',
        'catalog.can_change_is_published'
    ]

    def dispatch(self, request, *args, **kwargs):
        product = self.get_object()
        user = request.user

        is_owner = product.owner == user
        is_manager = user.groups.filter(name='manager').exists()
        is_superuser = user.is_superuser

        if not (is_owner or is_manager or is_superuser):
            return HttpResponseForbidden("У вас нет прав для редактирования этого продукта.")

        return super().dispatch(request, *args, **kwargs)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        user = self.request.user
        is_superuser = user.is_superuser

        if (user.groups.filter(name='manager').exists() or is_superuser) and self.object.owner != user:
            allowed_fields = ['description', 'category', 'is_published']
            form.fields = {key: form.fields[key] for key in allowed_fields if key in form.fields}

        return form

    def get_success_url(self):
        return reverse('product_detail', args=[self.object.id])


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('product_list')
    template_name = 'product_confirm_delete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        product = self.get_object()

        context['is_owner'] = product.owner == user
        context['is_manager'] = user.groups.filter(name='manager').exists()
        return context


def contact_us(request):
    return render(request, 'contact_us.html')

catalog/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Online Store{% endblock %}</title>

    <!-- CSS Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/pricing.css' %}">
    <link rel="manifest" href="{% static 'manifest.json' %}">
    <meta name="theme-color" content="#712cf9">

    <!-- Custom Styles -->
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            width: 100%;
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
            --bd-violet-bg: #712cf9;
            --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

            --bs-btn-font-weight: 600;
            --bs-btn-color: var(--bs-white);
            --bs-btn-bg: var(--bd-violet-bg);
            --bs-btn-border-color: var(--bd-violet-bg);
            --bs-btn-hover-color: var(--bs-white);
            --bs-btn-hover-bg: #6528e0;
            --bs-btn-hover-border-color: #6528e0;
            --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
            --bs-btn-active-color: var(--bs-btn-hover-color);
            --bs-btn-active-bg: #5a23c8;
            --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
            z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
            display: block !important;
        }
    </style>
</head>

<body>
<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>

<div class="container py-3">
    <header>
        <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
            <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94"
                     role="img"><title>Bootstrap</title>
                    <path fill-rule="evenodd" clip-rule="evenodd"
                          d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"
                          fill="currentColor"></path>
                </svg>
                <span class="fs-4">Online Store</span>
            </a>

            <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                {% if user.is_authenticated %}
                <p class="me-3 py-2 link-body-emphasis text-decoration-none">
                    Аккаунт: {{ user.email }}</p>
                <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'reset_password' %}">Сменить
                    пароль</a>
                <form class="me-3 py-2 link-body-emphasis text-decoration-none" action="{% url 'logout' %}"
                      method="post">
                    {% csrf_token %}
                    <button type="submit" class="me-3 py-2 link-body-emphasis text-decoration-none">Выйти</button>
                </form>
                {% else %}
                <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'login' %}">Войти</a>
                {% endif %}
                <a class="me-4 py-2 link-body-emphasis text-decoration-none"
                   href="{% url 'article-list' %}">Articles </a>
                <a class="me-3 py-2 link-body-emphasis text-decoration-none"
                   href="{% url 'product_list' %}">Products</a>
                <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'contact_us' %}">Contact
                    Us</a>
                <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'register' %}">Sign up</a>
            </nav>
        </div>

        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Online Store</h1>
            {% block description %}
            {% endblock %}
        </div>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                <small class="d-block mb-3 text-body-secondary">&copy; 2017–2024</small>
            </div>
            <div class="col-12 col-md">
            </div>
            <div class="col-6 col-md">
                <h5>About</h5>
                <ul class="list-unstyled text-small">
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team</a></li>
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Locations</a></li>
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Privacy</a></li>
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Terms</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<!-- JavaScript Files -->
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/color-modes.js' %}"></script>
</body>
</html>

catalog/templates/contact_us.html
{% extends 'base.html' %}
 
 {% block title %}Contact Us{% endblock %}
 
 {% block description %}
     <p class="lead">We would love to hear from you! Please fill out the form below to get in touch with us.</p>
 {% endblock %}
 
 {% block content %}
 <div class="container">
     <h2>Contact Us</h2>
     <form action="{% url 'contact_us' %}" method="post">
         {% csrf_token %}
         <div class="mb-3">
             <label for="name" class="form-label">Name</label>
             <input type="text" class="form-control" id="name" name="name" required>
         </div>
         <div class="mb-3">
             <label for="phone" class="form-label">Phone Number</label>
             <input type="tel" class="form-control" id="phone" name="phone" required>
         </div>
         <div class="mb-3">
             <label for="message" class="form-label">Message</label>
             <textarea class="form-control" id="message" name="message" rows="4" required></textarea>
         </div>
         <button type="submit" class="btn btn-primary">Submit</button>
     </form>
     <div class="mt-4">
         <h5>Our Address:</h5>
         <p>1234 Main St,<br>City, Country 12345</p>
     </div>
 </div>
 {% endblock %}

catalog/templates/main_menu.html
{% extends 'base.html' %}

{% block title %}Product List{% endblock %}
{% block description %}
<p class="fs-5 text-body-secondary">Исключительный онлайн-шопинг: широкий ассортимент товаров от ведущих
    брендов, быстрая доставка и превосходное качество обслуживания. Наша платформа предлагает удобный поиск,
    подробные описания и отзывы покупателей для информированного выбора. Гарантируем безопасные оплату и
    возврат, чтобы ваше шопинг-опыт был максимально приятным.</p>{% endblock %}

{% block content %}
{% endblock %}

catalog/templates/product_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Delete article{% endblock %}

{% block description %}
<p class="lead">Are you sure you want to delete this product?</p>
<h2>Delete Product</h2>
{% endblock %}

{% block content %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete the product "{{ object.title }}"?</p>
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'product_list' %}" class="btn btn-secondary">Cancel</a>
    </form>

    <div class="mt-4">
        <h5>Our Address:</h5>
        <p>1234 Main St,<br>City, Country 12345</p>
    </div>
</div>
{% endblock %}

catalog/templates/product_create.html
{% extends 'base.html' %}

{% block title %}Create product{% endblock %}

{% block description %}
    <p class="lead"></p>
    <h2>Create product</h2>

{% endblock %}

{% block content %}
    <div class="container">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            {% if object %}
                <button class="btn-outline-primary" type="submit">Change</button>
            {% else %}
                <button class="btn-outline-primary" type="submit">Publish</button>
            {% endif %}
        </form>

        <div class="mt-4">
            <h5>Our Address:</h5>
            <p>1234 Main St,<br>City, Country 12345</p>
        </div>
    </div>
{% endblock %}

catalog/templates/product_detail.html
{% extends 'base.html' %}
{% load image_tags %}
{% block title %}{{ product.name }}{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="card">
        <div class="row g-0">
            <div class="col-md-4">
                {% if product.image %}
                {% image_tag product.image.url 300 300 %}
                {% else %}
                <img src="https://via.placeholder.com/400" class="img-fluid rounded-start"
                     alt="No image available">
                {% endif %}
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">name -> {{ product.name }}</h5>
                    {% if product.owner %}
                    <h6 class="card-title">owner -> {{ product.owner }}</h6>
                    {% else %}
                    <h6 class="card-title">owner -> Отсутствует</h6>
                    {% endif %}
                    <p class="card-text"><strong>Category:</strong> {{ product.category }}</p>
                    <p class="card-text">{{ product.description }}</p>
                    <p class="card-text"><strong>Price per unit:</strong> ${{ product.price_per_unit }}</p>
                    <p class="card-text"><small class="text-muted">Created at: {{ product.created_at }}</small></p>
                    <p class="card-text"><small class="text-muted">Updated at: {{ product.updated_at }}</small></p>
                    <a href="{% url 'product_list' %}" class="btn btn-primary">Back to Products</a>
                    {% if product.owner == user or perms.catalog.change_product %}
                    <a href="{% url 'product_update' product.id %}" class="btn bg-body-secondary">Change</a>
                    {% endif %}
                    {% if product.owner == user or perms.catalog.delete_product %}
                    <a href="{% url 'product_delete' product.id %}" class="btn btn-primary">Delete</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/product_list.html
{% extends 'base.html' %}

{% block title %}Product List{% endblock %}
{% block description %}
<p class="fs-5 text-body-secondary">Продукты</p>
<a href="{% url 'product_create' %}" class="btn btn-primary">Create product</a>{% endblock %}

{% block content %}
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    {% for item in products_with_versions %}
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ item.product.name }}</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ item.product.price_per_unit }}$</h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>{{ item.product.description|truncatechars:100 }}</li>
                </ul>
                {% if item.active_version %}
                <p><strong>Active Version:</strong> {{ item.active_version.version_name }}
                                ({{ item.active_version.version_number }})</p>
                {% else %}
                <p><strong>No active version available.</strong></p>
                {% endif %}
                <a href="{% url 'product_detail' item.product.id %}"
                           class="w-100 btn btn-lg btn-primary">Buy!</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}